image:
  repository: onelabscontainerregistry.azurecr.io/prospeku-web

deployment:
  enabled: true

service:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: prospeku.com
      paths:
        - path: /
          backend:
            servicePort: 8080

resources:
  limits:
    cpu: 50m
    memory: 64Mi
  requests:
    cpu: 30m
    memory: 32Mi

