image:
  repository: onelabscontainerregistry.azurecr.io/prospeku-web

deployment:
  enabled: true

service:
  enabled: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Robots-Tag 'noindex, nofollow, noarchive' always;
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: prospeku-sit.onelabs.dev
      paths:
        - path: /
          backend:
            servicePort: 8080
  tls:
    - secretName: letsencrypt-wildcard-certs
      hosts:
        - prospeku-sit.onelabs.dev